export const PRODUCTS = [
  {
    id: "bar-signature-72",
    name: "Signature 72% Velvet Dark",
    price: 650, // cents
    rating: 4.9,
    tags: ["bar","classic"],
    weight: "90g",
    img: "https://images.unsplash.com/photo-1548907040-4baa42d1094b?q=80&w=1200&auto=format&fit=crop",
    blurb: "Silky dark with a milk-like finish. Single-origin cocoa, slow-conched for 72 hours.",
    notes: ["caramel","vanilla","hazelnut"],
  },
  {
    id: "truffles-velour",
    name: "Velour Truffle Collection",
    price: 2400,
    rating: 5,
    tags: ["truffles","gift"],
    weight: "16 pcs",
    img: "https://images.unsplash.com/photo-1633933444287-5d4c6f2b1d28?q=80&w=1200&auto=format&fit=crop",
    blurb: "Hand-rolled ganache enrobed in gold-dusted cocoa. Our most gifted box.",
    notes: ["cream","almond","cocoa"],
  },
  {
    id: "bar-almond-gold",
    name: "Almond Gold Crunch",
    price: 725,
    rating: 4.8,
    tags: ["bar","nuts"],
    weight: "100g",
    img: "https://images.unsplash.com/photo-1606313564200-e75d5e30476d?q=80&w=1200&auto=format&fit=crop",
    blurb: "Roasted Marcona almonds in velvet-dark couverture with a creamy snap.",
    notes: ["almond","butter","sea salt"],
  },
  {
    id: "box-grand-cru",
    name: "Grand Cru Gift Tower",
    price: 6400,
    rating: 4.9,
    tags: ["gift","assortment"],
    weight: "3-tier",
    img: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=1200&auto=format&fit=crop",
    blurb: "Three tiers of bars, truffles, and dragées wrapped in satin black & gold.",
    notes: ["assorted","celebration"],
  },
  {
    id: "dragees-rose",
    name: "Rose Petal Dragées",
    price: 1400,
    rating: 4.7,
    tags: ["dragees","floral"],
    weight: "150g",
    img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1200&auto=format&fit=crop",
    blurb: "Crisp centers tumbled in rose-kissed velvet dark—finished with pink shimmer.",
    notes: ["rose","berry","cocoa"],
  },
  {
    id: "bar-seasalt",
    name: "Sea Salt Silk 65%",
    price: 675,
    rating: 4.8,
    tags: ["bar","salt"],
    weight: "90g",
    img: "https://images.unsplash.com/photo-1629648145358-0a1d9d8278b9?q=80&w=1200&auto=format&fit=crop",
    blurb: "Delicate flakes of sea salt accentuate the milk-like finish of our dark.",
    notes: ["sea salt","toffee","cream"],
  },
];

// Map product -> Stripe Price ID (replace with your real price IDs from Stripe dashboard)
export const PRICE_IDS = {
  "bar-signature-72": process.env.NEXT_PUBLIC_PRICE_BAR_SIGNATURE_72 || "price_XXXX_signature72",
  "truffles-velour": process.env.NEXT_PUBLIC_PRICE_TRUFFLES_VELOUR || "price_XXXX_truffles",
  "bar-almond-gold": process.env.NEXT_PUBLIC_PRICE_BAR_ALMOND_GOLD || "price_XXXX_almond",
  "box-grand-cru": process.env.NEXT_PUBLIC_PRICE_BOX_GRAND_CRU || "price_XXXX_grandcru",
  "dragees-rose": process.env.NEXT_PUBLIC_PRICE_DRAGEES_ROSE || "price_XXXX_rose",
  "bar-seasalt": process.env.NEXT_PUBLIC_PRICE_BAR_SEASALT || "price_XXXX_seasalt",
};
